spring:
  sql:
    init:
      mode: always
  application:
    name: dtltm
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5001}/${DB_NAME:db}
    username: ${DB_USERNAME:admin_user}
    password: ${DB_PASSWORD:password}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: ${KAFKA_BROKER:localhost:9094}
server:
  port: ${SERVER_PORT:20001}